### ISSUE TITLE
Polestar P3.0.3 USB permission dialog

### ISSUE THREAD

**Issue by nopunk321** [MoleMan1024/audiowagon#142]
Since the recent Android update to Polestar 2, the USB permission dialog popup is now blocked when the car is in motion (UK) as the system displays the "Unavailable, for your safety" screen over the top.

It works fine when stationary, so it has become necessary to launch the app before starting a new drive. But I normally forget..

version 2.6.7

(This may be more of a Polestar problem outside of your software to be fair).

**Comment by MoleMan1024** [comment]
Sorry, I did not add this "Unavaible for your safety" popup so I can not remove it either.

**Comment by Piedrosvs** [comment]
As far as I've seen by now, the car must be in "N" to be able to tap the permission dialog. It is a real pain in the @$$, but indeed probably nothing you can solve.

**Comment by micksmothers** [comment]
Or as MoleMan mentioned just come to a complete stop. You don't have to put it in Park or Neutral.

**Comment by nopunk321** [comment]
I emailed Polestar yesterday and they said they were aware and working on it, but had no further information. I dont know how truthful they are about these things or maybe just a standard response.

**Comment by Tuxie** [comment]
> they said they were aware and working on it, but had no further information

That usually means that there is a ticket for it that will likely never get high enough priority to ever get implemented because all developers will always have something more important to work on.

The only chance is that some individual developer who is also annoyed by the problem will take it on during a hackathon and be able to implement enough of it that what's left will be considered a low enough hanging fruit for managers to say "ok, then" to finalizing and merging it to the production code.

**Comment by JazzySOB** [comment]
Received te latest update on my Volvo XC40 to version 3.6.4 yesterday and the issue with the pop-up is still there. I think it will never be solved as Google does not want it to fix.

**Comment by nopunk321** [comment]
Interesting; the update before 3.6 4 that enabled Andriod Auto on the
Polestar 2 actually fixed it for me.
