### ISSUE TITLE
Make re-indexing faster or allow user to select when to run it

### ISSUE THREAD

**Issue by MoleMan1024** [MoleMan1024/audiowagon#21]
Received from a beta tester:

As a car driver,
I want the re-indexing process to run faster
so that I can play back my music earlier.

**Comment by MoleMan1024** [comment]
With large libraries this is more annoying. I could introduce a setting to either auto-index or index by user request only.

**Comment by lvitalis** [comment]
Is re-indexing required because of how Android Automotive handles the USB drive access ?
In my Volvo V60, re-indexing only occurred when a change was detected on the USB drive.
The rest of the time, database was ready when entering the car.

I would not mind having to manually trigger a re-index in AudioWagon, when I add a new album folder, once every month.
To avoid re-scanning every time I enter the car.

**Comment by MoleMan1024** [comment]
@lvitalis : "when a change was detected" --> so your Volvo was doing indexing as well (it might have done it in the background or not visible to you though). You need to somehow detect that files on the filesystem have changed and update those. To do that you need to look at every file. This is what the indexing is doing, see [what happens during indexing?](https://moleman1024.github.io/audiowagon/faq.html#what-happens-during-indexing)

**Comment by lvitalis** [comment]
@MoleMan1024 : I made an error in my comment. The Volvo would only rescan if I removed and re-inserted the USB drive.
And the rescan was much more quicker than the initial database creation.

Do you rescan all files ? 
If a file is modified, its folder will also have an updated modification date.
Maybe you could skip scanning files inside a folder that has an identical modification date.

**Comment by micksmothers** [comment]
Just seeing this - I can add a backlog item:

As a car driver
I would like to select an option to manually reindex the USB drive
and disable automatic reindexing
and persist the artist/album to track relationships
so that I can have the previous indexing results quickly available on startup
and still be able to play by artist or album

I did read through the FAQ and I saw that we could turn off reindexing, but that limited the ability to play by metadata tags it seems. Hopefully I didn't misunderstand.

**Comment by MoleMan1024** [comment]
In version 1.2.0 you can now select when to index the files on the USB drive:

- automatically when USB drive connected
- manually via the settings
- never

The second setting is new and allows users to select when they want to re-index their database themselves (e.g. when they know they have added new files). This will remove the need for the initial indexing process.

**Comment by MoleMan1024** [comment]
Just found out that the comment: "If a file is modified, its parent folder will also have an updated modification date." is only true for NTFS or others, not for FAT32.
